# Generated by Django 5.0.7 on 2024-07-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
