# Generated by Django 5.0.7 on 2024-07-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comments_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
    ]
